### ISSUE TITLE
New User Onboarding survey

### ISSUE THREAD

**Issue by Spell2az** [chingu-x/feedback#46]
from console:
 manifest.json:1 Manifest: Line: 1, column: 1, Unexpected token.
DynamicFormContainer.jsx:204 Missing hiddenData for: timezone
(anonymous) @ DynamicFormContainer.jsx:204

Unable to proceed after form has been filled out. Button is still showing incomplete.

**Comment by tropicalchancer** [comment]
Hi @Spell2az, 

Thanks for reaching out! 

Could you possibly send some screenshots so we can better navigate what the problem is?

**Comment by Spell2az** [comment]
[cid:image003.png@01D47687.34C2EF40]
I hope I didn’t miss anything.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by tropicalchancer** [comment]
Hey @Spell2az, 

No worries, we just launched so there's bound to be bugs - and if you missed something, that is our fault - it means we need to fix something so that members can't miss things. 😃 

Also @Spell2az can you try to resend that image? It doesn't seem to have went through.

**Comment by Spell2az** [comment]
If it wont go through, let me know I will upload it somewhere and send you link.
[cid:image001.png@01D4768B.E4796640]
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by the-vampiire** [comment]
anyone else still having this issue?

i am not able to reproduce it. suggestions to try (if you havent already):
- log out of chingu
- clear local storage entries for beta.chingu.io
- hard refresh (ctrl + shift + R) to clear cache
- log back in
- try register form again

if these steps work for you or you find a different way of fixing it post it so others can see. if the problem persists can you copy over any errors / warnings / logs from the dev tools so i can try to debug it

**Comment by Spell2az** [comment]
DynamicFormContainer.jsx:204                                 Missing hiddenData for: timezone    
(anonymous) @ DynamicFormContainer.jsx:204
(anonymous) @ DynamicFormContainer.jsx:181
value @ DynamicFormContainer.jsx:41
vr @ react-dom.production.min.js:227
hr @ react-dom.production.min.js:218
pr @ react-dom.production.min.js:217
sr @ react-dom.production.min.js:214
nr @ react-dom.production.min.js:212
enqueueForceUpdate @ react-dom.production.min.js:134
(anonymous) @ react.production.min.js:13
(anonymous) @ react-apollo.browser.umd.js:389
next @ react-apollo.browser.umd.js:371
p @ Observable.js:130
d @ Observable.js:165
value @ Observable.js:219
(anonymous) @ ObservableQuery.js:337
next @ ObservableQuery.js:337
(anonymous) @ QueryManager.js:407
(anonymous) @ QueryManager.js:698
(anonymous) @ QueryManager.js:697
(anonymous) @ QueryManager.js:692
next @ QueryManager.js:749
p @ Observable.js:130
d @ Observable.js:165
value @ Observable.js:219
(anonymous) @ dedupLink.js:60
next @ dedupLink.js:60
p @ Observable.js:130
d @ Observable.js:165
value @ Observable.js:219
next @ index.js:41
p @ Observable.js:130
d @ Observable.js:165
value @ Observable.js:219
p @ Observable.js:130
d @ Observable.js:165
value @ Observable.js:219
(anonymous) @ httpLink.js:95
Promise.then (async)
(anonymous) @ httpLink.js:93
e @ Observable.js:183
value @ Observable.js:262
(anonymous) @ index.js:96
Promise.then (async)
(anonymous) @ index.js:95
e @ Observable.js:183
value @ Observable.js:262
(anonymous) @ index.js:23
e @ Observable.js:183
value @ Observable.js:262
(anonymous) @ dedupLink.js:55
e @ Observable.js:183
value @ Observable.js:262
(anonymous) @ QueryManager.js:729
(anonymous) @ QueryManager.js:727
(anonymous) @ QueryManager.js:260
(anonymous) @ QueryManager.js:585
(anonymous) @ ObservableQuery.js:344
(anonymous) @ ObservableQuery.js:312
(anonymous) @ ObservableQuery.js:43
e @ Observable.js:183
value @ Observable.js:262
(anonymous) @ react-apollo.browser.umd.js:363
(anonymous) @ react-apollo.browser.umd.js:466
vr @ react-dom.production.min.js:227
hr @ react-dom.production.min.js:218
pr @ react-dom.production.min.js:217
sr @ react-dom.production.min.js:214
nr @ react-dom.production.min.js:212
enqueueForceUpdate @ react-dom.production.min.js:134
(anonymous) @ react.production.min.js:13
(anonymous) @ react-apollo.browser.umd.js:389
next @ react-apollo.browser.umd.js:371
p @ Observable.js:130
d @ Observable.js:165
value @ Observable.js:219
(anonymous) @ ObservableQuery.js:337
next @ ObservableQuery.js:337
(anonymous) @ QueryManager.js:407
(anonymous) @ QueryManager.js:698
(anonymous) @ QueryManager.js:697
(anonymous) @ QueryManager.js:692
next @ QueryManager.js:749
p @ Observable.js:130
d @ Observable.js:165
value @ Observable.js:219
(anonymous) @ dedupLink.js:60
next @ dedupLink.js:60
p @ Observable.js:130
d @ Observable.js:165
value @ Observable.js:219
next @ index.js:41
p @ Observable.js:130
d @ Observable.js:165
value @ Observable.js:219
p @ Observable.js:130
d @ Observable.js:165
value @ Observable.js:219
(anonymous) @ httpLink.js:95
Promise.then (async)
(anonymous) @ httpLink.js:93
e @ Observable.js:183
value @ Observable.js:262
(anonymous) @ index.js:96
Promise.then (async)
(anonymous) @ index.js:95
e @ Observable.js:183
value @ Observable.js:262
(anonymous) @ index.js:23
e @ Observable.js:183
value @ Observable.js:262
(anonymous) @ dedupLink.js:55
e @ Observable.js:183
value @ Observable.js:262
(anonymous) @ QueryManager.js:729
(anonymous) @ QueryManager.js:727
(anonymous) @ QueryManager.js:260
(anonymous) @ QueryManager.js:585
(anonymous) @ ObservableQuery.js:344
(anonymous) @ ObservableQuery.js:312
(anonymous) @ ObservableQuery.js:43
e @ Observable.js:183
value @ Observable.js:262
(anonymous) @ react-apollo.browser.umd.js:363
(anonymous) @ react-apollo.browser.umd.js:466
vr @ react-dom.production.min.js:227
hr @ react-dom.production.min.js:218
pr @ react-dom.production.min.js:217
sr @ react-dom.production.min.js:214
nr @ react-dom.production.min.js:212
enqueueSetState @ react-dom.production.min.js:133
(anonymous) @ react.production.min.js:13
(anonymous) @ Router.js:70
n @ createTransitionManager.js:46
(anonymous) @ createTransitionManager.js:65
notifyListeners @ createTransitionManager.js:64
O @ createBrowserHistory.js:78
(anonymous) @ createBrowserHistory.js:169
n @ createTransitionManager.js:36
P @ createBrowserHistory.js:149
(anonymous) @ index.jsx:44
r @ runtime.js:62
(anonymous) @ runtime.js:296
(anonymous) @ runtime.js:114
r @ main.f6ffbb03.js:79717
(anonymous) @ main.f6ffbb03.js:79717
Promise.then (async)
r @ main.f6ffbb03.js:79717
(anonymous) @ main.f6ffbb03.js:79717
(anonymous) @ main.f6ffbb03.js:79717
e @ main.f6ffbb03.js:79722
vr @ react-dom.production.min.js:227
hr @ react-dom.production.min.js:218
pr @ react-dom.production.min.js:217
sr @ react-dom.production.min.js:214
nr @ react-dom.production.min.js:212
Er @ react-dom.production.min.js:234
wr @ react-dom.production.min.js:234
(anonymous) @ react-dom.production.min.js:242
(anonymous) @ react-dom.production.min.js:245
br @ react-dom.production.min.js:231
Ir @ react-dom.production.min.js:245
render @ react-dom.production.min.js:247
(anonymous) @ index.js:35
t @ bootstrap 94b32ed995a6723230aa:19
(anonymous) @ main.f6ffbb03.js:45947
t @ bootstrap 94b32ed995a6723230aa:19
(anonymous) @ bootstrap 94b32ed995a6723230aa:62
(anonymous) @ bootstrap 94b32ed995a6723230aa:62


This is what I get besides this one Manifest: Line: 1, column: 1, Unexpected token.

I did try your suggestions on Firefox and also Edge but it didn't work.

**Comment by the-vampiire** [comment]
This is the logs after you tried the above steps?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by the-vampiire** [comment]
Are you available tomorrow? We can screen share and debug it together. I’m really curious about what the cause is. It seems to only be affecting you and one other. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Spell2az** [comment]
Sure you can find me on slack in voyage 6 channel.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by jenbird** [comment]
Cleared local storage etc as advised above then tested again on Chrome. 
Form data is there but shows as false/field_errors probably due to timezone issue mentioned before.
(test@gmail.com used so I could hide my email but using my email address doesn't work anyway)
Class on submit button still shows as `.form-btn--disabled`
<img width="1181" alt="screenshot 2018-11-08 at 15 12 41" src="https://user-images.githubusercontent.com/13733671/48207635-fd440f00-e368-11e8-8b1a-46afe5df6f31.png">

**Comment by jenbird** [comment]
is it this...
components/index.jsx line 15
remove double curly brackets from timezone variable?
`hiddenData={timezone}`
thanks

**Comment by the-vampiire** [comment]
HiddenData (as ominous as it may sound lol) is just an object with values for input type “hidden”. So it needs the double curlies (outer for passing a non string prop, inner for representing the hiddenData Object



<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by the-vampiire** [comment]
sorry for the delay i was at the vet. working on a solution now. seems to be that your timezone offsets arent being picked up. the function is compatible with all modern browsers so im not sure what the reason is.

in any case we are moving the timezone question (used in team formation - for the record) to your (private, `/profile`) page. will let you guys know when it is up.

**Comment by the-vampiire** [comment]
@Spell2az @jennifersmithuk hey the changes are live. log out, clear local storage, then log back in and you should be able to fill out and submit now!

let me know if there are still any problems or if its ok to mark this issue as solved

**Comment by Spell2az** [comment]
Sorted. Thank you. Could you please describe what was the problem and how did you solve it as it only affected couple of people.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by jenbird** [comment]
@the-vampiire brilliant, thank you. have submitted form now. would also be interested in problem/solution please.

**Comment by the-vampiire** [comment]
I’m wondering if due to a browser privacy setting time zone offset isn’t being calculated. You’d think it would show null though. 

The fix here was more of an upgrade. Got rid of implicit time zones altogether. The original intention was to calculate it automatically to prevent user error. 

Now it’s a selectable that we will include in the pre voyage update section. We’ll see if there are a lot of errors but I think most of us know our time zones so it shouldn’t be a problem. 

I never found d out the cause because I didn’t want to burden you guys with debugging. Figured you’d be happier with a solution than a debugging process. 

But if you are as curious as I am. Can you try running

`const d = new Date();`
`d.getTimezoneOffset();`

In your browser dev tools. Let me know what the result is? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jenbird** [comment]
@the-vampiire thanks for sorting issue and explaining too.
I did this to try and debug before my last comment. Have just tried again now and get the same result which is 0 (I'm GMT 0) so it is, and was, being calculated. 
¯\_(ツ)_/¯
No idea why timezone was showing as an empty string and throwing a field error. 
Can't recreate any more as I've now completed form since fix but if there's anything I can do to help let me know.

**Comment by jenbird** [comment]
@the-vampiire just took look through commits out of curiosity. As `getTimezoneOffset()` returns a number rather than the Date object is this what is causing the issue as DynamicForm.propTypes says `hiddenData: PropTypes.object` ?

**Comment by the-vampiire** [comment]
@jennifersmithuk love the curiosity! actually the prop type is correct. `hiddenData` is an object of the form
```js
hiddenData = { field_name: 'value', field_name: number, ... }
```

it lets you pass in any number of field_name/value pairs to provide data for hidden input types.

its interesting that your value is 0. somehow that must have been translated into a falsey string equivalent (`''`). its going to bug me but ive got too much else to work on to dig much further right now.

if we find that user selected timezones are a problem and we return to implicit timezones ill definitely figure it out and let you know. thanks again for the heads up
