### ISSUE TITLE
Application confirmation

### ISSUE THREAD

**Issue by arielbk** [chingu-x/feedback#47]
I was slightly confused after finishing the application when I was quickly brought back to the main page. Some kind of confirmation and 'congratulations' would be great :)

**Comment by tropicalchancer** [comment]
Hi @arielbk! 

Thanks for reaching out and that's a fantastic suggestion! You're definitely right 💯 

We'll add that to the backlog. 🔥

**Comment by the-vampiire** [comment]
Issue moved to [chingu-x/chingu-frontend #163](https://github.com/chingu-x/chingu-frontend/issues/163) via [**ZenHub**](https://www.zenhub.com/)
