### ISSUE TITLE
New Voyage User Application - Submission - GraphQL duplicate form

### ISSUE THREAD

**Issue by ir3ne** [chingu-x/feedback#56]
Hi,
when I click on 'submit' button I have this Error message: 'GraphQL error: Duplicate form submission'  and a 'go back' button. 

<img width="509" alt="screenshot 2018-11-07 at 22 40 28" src="https://user-images.githubusercontent.com/23403047/48300779-88e1ab00-e4e3-11e8-8e2f-b88633edbc8e.png">

When I click 'go back' I have my profile with some of my info. 

<img width="405" alt="screenshot 2018-11-10 at 10 52 04" src="https://user-images.githubusercontent.com/23403047/48300798-b890b300-e4e3-11e8-8b89-ce2196306277.png">

But when I go in the 'Voyage Portal' the button 'Apply' remains there as if I had not done the application.

<img width="691" alt="screenshot 2018-11-10 at 10 52 35" src="https://user-images.githubusercontent.com/23403047/48300787-a31b8900-e4e3-11e8-89f9-134e82678ecc.png">

Thanks,

Irene

**Comment by FoteiniK** [comment]
I'm having the same issue.

**Comment by diskomotech** [comment]
I'm also having the same problem.

Initially, I had a different GraphQL error message which I didn't take a proper note of but was something along the lines of '255 characters exceeded'. When I have then tried re-submitting my application I keep getting this 'duplicate form' error message.

**Comment by cvonwilczur** [comment]
@diskomotech 

I had the same issue; uncertain if my first application attempt was accepted.

**Comment by the-vampiire** [comment]
i believe the cause is the same as #52 
the issue was the character limits for background, coding history, and interests. i upped them to 1000 now.

when the character limit was passed it failed to put the content onto your profiles (and set your statuses correctly). i am going to port over your data and fix your statuses now.

if your issue was caused by something else let me know so i can look into it

**Comment by cvonwilczur** [comment]
@the-vampiire Awesome; no further action needed on our end?

**Comment by the-vampiire** [comment]
[diskomotech](https://beta.chingu.io/profile/diskomotech)
[cvonwilczur](https://beta.chingu.io/profile/cvonwilczur)
[ir3ne](https://beta.chingu.io/profile/ir3ne)
[FoteiniK](https://beta.chingu.io/profile/FoteiniK)

youre profiles have all been fixed. you can go back [to the voyage page](https://beta.chingu.io/voyage/application/1) and complete your registration.

let me know if there are any other problems. thanks for the heads up

**Comment by ir3ne** [comment]
Perfect! Thanks a lot:)

**Comment by FoteiniK** [comment]
Yep! It's all good! Thank you @the-vampiire !

**Comment by diskomotech** [comment]
All working for me too. Thanks very much!
