### ISSUE TITLE
Unable to register a new user

### ISSUE THREAD

**Issue by louisdante9** [chingu-x/feedback#57]
As a new user i am unable to register successfully also the console show too much info about the technology being for example i am able to debug that u are using graphql and data being sent to the backend. This is cool for production code don't you think?

**Comment by the-vampiire** [comment]
what happens when you try to register?

the client code is [open source](https://github.com/chingu-x/chingu-frontend) and the network tab will always show unencrypted request/response bodies. if you have specific suggestions for improvement well gladly take them (or a PR if youre up for it!)

**Comment by the-vampiire** [comment]
Hey man I’m going to close this. Haven’t heard back from you I assume the fixes put in for the other issues has resolved yours. If you’re still stuck I’ll reopen it on your response. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
