### ISSUE TITLE
Is my registration form correct?

### ISSUE THREAD

**Issue by evgeshabond** [chingu-x/feedback#59]
Pls, check my form. I am scared of losing Chingu chance :) Thank you!

**Comment by ninette98** [comment]
Pls, check my form. I am scared of losing Chingu chance :) Thank you!

**Comment by the-vampiire** [comment]
can you give me more detail of what your concern is / what happened?

**Comment by the-vampiire** [comment]
i just checked the system. your applications were received correctly. nothing to worry about.

**Comment by ninette98** [comment]
i didn't received my team yet so i'm wondering if there is a problem with
my registration or i should wait or what?

**Comment by ninette98** [comment]
i didn't received  my workspace details yet
