### ISSUE TITLE
When does it start? I'm confused :)

### ISSUE THREAD

**Issue by adrianmanea** [chingu-x/feedback#60]
Hei guys, it's my first Voyage, can someone let me know the procedure? My profile is still on pending and the voyage should start today?

> EDIT: > 🔥Reminder — The Winter Beta Cohort Onboarding starts November 19th & teams will be released 3–5 days later.

https://medium.com/chingu/the-winter-beta-cohort-session-prep-handbook-9fd9be0abd1a

I won't freak out now :)

PS. I'll keep the issue open just to remind to the other folks like me that we need to be patient 👍

**Comment by tropicalchancer** [comment]
@adrianmanea - did you receive the reminder email sent today about the cohort starting? 

Invites go out in 2 hours, btw.
