### ISSUE TITLE
Team signup form didn't successfully submit until today.

### ISSUE THREAD

**Issue by Ephygtz** [chingu-x/feedback#61]
I'm **Ephraim** from Nairobi Kenya, and I have been super looking forward to leveling up my skills on this Voyage but just noticed that my *team signup form didn't successfully submit*. I have just resubmitted the form, **is it too late to be placed in a team?**

I would really appreciate if considered or join a waiting list in case there's an opening in one of the teams. Anxiously waiting for your feedback.

Warmly,

**Comment by the-vampiire** [comment]
Hey sorry about the previous bug. You’re new application went through. I passed your email to chance to send you the invite.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Ephygtz** [comment]
> Hey sorry about the previous bug. You’re new application went through. I passed your email to chance to send you the invite.
> 
> Sent with [GitHawk](http://githawk.com)

Hi @the-vampiire 

I still haven't received any feedback yet, is there anything more I could do about this? Warmly
