### ISSUE TITLE
No sign of team signup

### ISSUE THREAD

**Issue by alc080341** [chingu-x/feedback#62]
I received an email with the following info:

***Go to https://beta.chingu.io/ to fill out the Team Signup form. This is to get you into the new Chingu platform. You will need to signup at the URL above, authenticate with github, then navigate to the "Voyage portal" to fill out the team signup form.

I cannot seem to find the team signup form on the site after authentication with github - am I missing something?

Best,

Tony

**Comment by the-vampiire** [comment]
Hey man sorry about the confusing wording in the email. If you go to https://beta.chingu.io/voyage you can see the winter beta voyage. Just hit apply on there and fill out the application.

I’m not sure if the deadline has passed but when you finish applying let me know and I’ll pass your info on to the team. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by alc080341** [comment]
Hi,
No problem - I have applied - thanks for your help!
