### ISSUE TITLE
Beta team application error

### ISSUE THREAD

**Issue by ZumDeWald** [chingu-x/feedback#63]
When submitting my application through the beta site and it gave an error saying “over character limit”, when I submitted it a second time it gave the error “duplicate submission”.

The submission never went through correctly and Chance had to manually add me.

**Comment by the-vampiire** [comment]
This happened today?

**Comment by ZumDeWald** [comment]
No. This happened last week. I should have reported it then but when it came back as “duplicate application” I thought it had gone through despite the initial error.

**Comment by the-vampiire** [comment]
alright I fixed your status so you should be able to complete the voyage form now.

do you want me to copy over your background, coding history, and interests from your application or leave the info you have currently on your profile?

**Comment by the-vampiire** [comment]
you can fill out your application [here](https://beta.chingu.io/voyage/application/1)

**Comment by ZumDeWald** [comment]
Info from the profile would be great, thanks!

**Comment by the-vampiire** [comment]
alright going to close this. let me know if there is any other issue. sorry about that it was due to incorrect character limit validation for those profile fields.

**Comment by ZumDeWald** [comment]
All set here, thanks Vampiire!
