### ISSUE TITLE
Member filled out form but not found on the list

### ISSUE THREAD

**Issue by tropicalchancer** [chingu-x/feedback#64]
Hey @the-vampiire or @TheSabby - when you get a moment could you take a look to see if @sipofwater (sipofwater) is on any of the applications in the database? 

He is a long-time member who was accepted, filled out the form on the beta site, but his application does not appear to be in the list I have. 

@sipofwater, could you also let us know when you filled it out if you can remember? 

Cheers 🍾

**Comment by tropicalchancer** [comment]
Hey @sipofwater - @the-vampiire got back to me and said he doesn't see your application in the database. To clarify - you filled out the application application form on beta.chingu.io with all the usual questions?

**Comment by sipofwater** [comment]
It would have been over the weekend of the 9th when the email came out requesting that the beta.chingu.io form be filled out that I completed it.

Knowing that there were problems, I kept an eye on the page upon submission of the form and there was no indication of any error so I assumed it submitted correctly.

**Comment by tropicalchancer** [comment]
Can you try to submit it again? We've got no trace of any submission on our end.

Also where you can please sent screenshots so we can better navigate

**Comment by sipofwater** [comment]
I can't see the Apply button when I'm logged in.

![selection_999 697](https://user-images.githubusercontent.com/15894446/48869693-fff42a80-ed92-11e8-82f1-57d59ab2e74f.png)

![selection_999 698](https://user-images.githubusercontent.com/15894446/48869750-2a45e800-ed93-11e8-999f-f8de25d02417.png)

**Comment by tropicalchancer** [comment]
if you click on your profile picture, it should give you some navigation options. Can you try that?
