### ISSUE TITLE
Is it possible to change location

### ISSUE THREAD

**Issue by josue-rojas** [chingu-x/feedback#65]
On https://beta.chingu.io/profile the bottom of the profile picture it says 'Based in Afghanistan', is it possible to change that? 

![screen shot 2018-11-26 at 17 59 15](https://user-images.githubusercontent.com/10749061/49047315-12140580-f1a5-11e8-9168-764ceac48b10.png)

**Comment by the-vampiire** [comment]
we are working on a new strategy for handling location / timezone / nationality. i can update it manually for you though. what country do you want?

**Comment by josue-rojas** [comment]
United States is fine. thanks!

**Comment by the-vampiire** [comment]
![screen shot 2018-11-27 at 1 29 28 pm](https://user-images.githubusercontent.com/25523682/49103100-7b992000-f248-11e8-84e8-42b2e2da8d13.png)
