### ISSUE TITLE
Member not placed in a team but was accepted and application was submitted

### ISSUE THREAD

**Issue by tropicalchancer** [chingu-x/feedback#66]
Github username: jmejme

@the-vampiire @thinktwice13 - I cross-referenced jmejme's username in the team spreadsheet and didn't find it, but then looked at the all-submitted-applications spreadsheet and he was there (timestamp below). 

Application submission date: 2018-11-10 

I wonder if a few people were not transferred? Could be a bug of some kind?

**Comment by jmejme** [comment]
Hey ✌️

**Comment by the-vampiire** [comment]
looked into it. caught a bug related to your timezone.

affected members:
- @jmejme 
- @palimpZest
- @JustbeingD

all three have timezones set to the far end (+720 offset, U-12) and somehow they are not appearing in teamsort.

will keep you posted when we get it fixed.

**Comment by the-vampiire** [comment]
![screen shot 2018-11-27 at 1 05 33 pm](https://user-images.githubusercontent.com/25523682/49102080-d5e4b180-f245-11e8-9024-e4544385bec2.png)

are you sure these are your correct timezones? somehow i doubt you are all in the baker and howland islands...lol

**Comment by tanishbaansal** [comment]
hey .. i am so sorry but i had exams and now i don't know how to enroll in the program 
Can anyone do anything for it

**Comment by the-vampiire** [comment]
The voyage started last week. When we open applications for a new voyage you can find it at https://beta.chingu.io/voyage (maybe without the beta subdomain at that point). 

Hope you slayed your exams man. See you in the next one!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
