### ISSUE TITLE
Network error in every page except the home

### ISSUE THREAD

**Issue by ir3ne** [chingu-x/feedback#68]
Hi, I can't go into the pages like voyage portal, newsfeed and all the others because I have a 'Network Error' like in the screen below.
<img width="548" alt="screenshot 2018-11-28 at 08 42 48" src="https://user-images.githubusercontent.com/23403047/49136492-041bcd00-f2ea-11e8-9c84-dad9115b76c2.png">

**Comment by the-vampiire** [comment]
have you tried clearing the cache? were looking into an issue with netlify. on deployment its supposed to invalidate the previous build cache. but it isnt. the only solution so far is to manually clear the cache and refresh.

**Comment by ir3ne** [comment]
@the-vampiire you're right. It works now. Thanks
