### ISSUE TITLE
Wont show anything

### ISSUE THREAD

**Issue by MarioKrstevski** [chingu-x/feedback#76]
Network error: Response not successful: Received status code 400

**Comment by tropicalchancer** [comment]
Screenshot (thanks @MarioKrstevski for sending it):

![image](https://user-images.githubusercontent.com/15321359/49256027-08e99980-f42e-11e8-8ef9-8dc53aa6488b.png)

**Comment by serpient** [comment]
Is the entire site not responding -- what were you trying to do? 
 
If its the entire site, can you try doing a hard refresh (control + F5) and see if that helps the situation?
