### ISSUE TITLE
Inactive members to remove before github repos/teams are created (from Slack thread)

### ISSUE THREAD

**Issue by tropicalchancer** [chingu-x/feedback#77]
# Inactive slack username | Team name

- @ninette |  Bears-team-05

- @karen | geckos-team-04

- @shaonashan8 | bears-team-13 

- @mcwachira & @adrian stefan | geckos-team-19

-  @kalyantm | geckos-team-20 

-  @Ogundiji Bolade | geckos-team-21 

- @philchoi1 |  geckos-team-23.

- @tarafenton | bears-team-09

**Comment by the-vampiire** [comment]
# members removed from teams:
- [x] @ninette |  Bears-team-05
- [x] @tarafenton | bears-team-09
- [x] @shaonashan8 | bears-team-13 
- [x] @mcwachira & @adrian stefan | geckos-team-19
- [x] @kalyantm | geckos-team-20 
- [x] @philchoi1 |  geckos-team-23.

##  cant find these members. they arent using their github usernames in slack
- [x] @Ogundiji Bolade | geckos-team-21 
    - deactivated
    - Adroit11
- [x] @karen | bears-team-04
    - deactivated
    - minmaxdata

**Comment by the-vampiire** [comment]
# teams repaired
- [x] geckos team 19
  - moved to geckos 24
- [x] geckos team 24
  - add @Foteinik and @ahmed-sallam
- [x] geckos team 21
  - add eugene-prout to geckos 14
  - added jennifersmithuk to geckos 20
- [x] geckos team 20
  - added jen
- [x] bears team 5
- nothing, they started with 5, now they have 4
- [x] bears team 9
   - proposed to be merged with bears-team-4
- [x] bears team 13
    - No one extra to fit their timezone at the moment, the team was launched as a team of two and they seem to be progressing as that. Sent one member a message to double check
- [x] bears team 4
    - proposed to be merged with bears-team-9

**Comment by tropicalchancer** [comment]
Connected bears 9 and 4 and they will make a ticket if they decide to merge: 

![image](https://user-images.githubusercontent.com/15321359/49302598-d68c7a80-f4c7-11e8-919c-10eec2f8a8b7.png)

**Comment by ssaleem** [comment]
I am part of geckos-project-10 and I don't see any members in the team slack channel.
